[package]
name = "src"
version = "0.1.0"
edition = "2021"


[dependencies]
reqwest = { version = "0.11.13", features = ["json"] }
tokio = { version = "1", features = ["full"] }
json = "0.12.4"
reqwest_cookie_store = "0.5.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0"